codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: 80
        threshold: 3%
      patch:
        default:
          threshold: 3%
  ignore:
    - "soepy/__init__.py"
