{% set data = load_setup_py_data() %}

package:
  name: soepy
  version: {{ data.get('version') }}

source:
  path: ../soepy

requirements:
  build:
    - python {{ python }}
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - pyyaml
    - pytest
    - flake8

test:
  commands:
    - py.test
  files:
    - soepy/test/test_integration.py
    - soepy/test/test_quality.py
    - soepy/test/test_regression.py
    - soepy/test/test_unit.py
  requires:
    - pytest

about:
  home: https://github.com/OpenSourceEconomics/soepy
  license: MIT
  summary: 'Simulate and estimate a dynamic model of human capital.'