[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.gitignore
  | \.in
  | \.mypy_cache
  | \.tox
  | \.venv
  | docs
  | soepy-egg-info

)/
[build-system]
requires = ['setuptools', 'wheel']