name: Continuous Integration Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: soepy
          auto-update-conda: true
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}

      - name: Run pytest.
        shell: bash -l {0}
        run: pytest --cov-report=xml --cov=./

      - name: Upload coverage report.
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run pre-commits.
        shell: bash -l {0}
        run: |
          pre-commit install -f --install-hooks
          pre-commit run --all-files
